config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'contacts/new'
  post 'contacts' => 'contacts#create'


  get 'company' => 'pages#company'
  get 'contact' => 'pages#contact'
  get 'service' => 'pages#service'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true, length: {maximum:255},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    validates :message, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def company
  end

  def contact
  end

  def service
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= content_for?(:title) ? yield(:title) : "株式会社Easy"%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%# <meta name="description" content="株式会社Easy"/>  %>
  </head>

  <body>
    <header class="header">
      <div class="headerWrap">
        <div class="logo">
          <%= link_to image_tag("easy.png", width: '120',height: "80"), root_path %>
        </div>
        <nav class="header-menu">
          <%= link_to '会社概要', company_path, class:"info" %>
          <%= link_to 'お問い合わせ', contact_path, class:"info" %>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer class="footer">
        <div class="footer-left">
          <%= link_to '会社概要', company_path, class:"info" %>
          <%= link_to 'お問い合わせ', contact_path, class:"info" %>
        </div>
      <small class="copyright">&copy; Easy inc.</small>
    </footer>

  </body>
</html>

app/views/pages/co_info.html.erb
<div class="container">
  <ul class="company_list">
    <li class="company_info">
      <p class="company_info_title">会社名</p>
      <p class="company_info_content">株式会社Easy</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">所在地</p>
      <p class="company_info_content">東京都板橋区赤塚新町1-16-2</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">代表取締役</p>
      <p class="company_info_content">圃田洋貴</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">事業内容</p>
      <div class="company_info_content">
        <p>Webサービス運営</p>
        <p>Railsによるシステム開発</p>
        <p>HP・LP制作</p>
      </div>
    </li>
    <li class="company_info">
      <p class="company_info_title">設立日</p>
      <p class="company_info_content">2019年3月1日</p>
    </li>
  </ul>
    </p>
</div> 

app/views/pages/company.html.erb
<% content_for :title do %>
 株式会社Easy　-会社概要-
<% end %>
<h1 class="page_title">会社概要</h1>
<div class="container">
  <ul class="company_list">
    <li class="company_info">
      <p class="company_info_title">会社名</p>
      <p class="company_info_content">株式会社Easy</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">所在地</p>
      <p class="company_info_content">東京都板橋区赤塚新町1-16-2</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">代表取締役</p>
      <p class="company_info_content">圃田洋貴</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">事業内容</p>
      <div class="company_info_content">
        <p>Webサービス運営</p>
        <p>Railsによるシステム開発</p>
        <p>HP・LP制作</p>
      </div>
    </li>
    <li class="company_info">
      <p class="company_info_title">設立日</p>
      <p class="company_info_content">2019年3月1日</p>
    </li>
    <li class="company_info">
      <p class="company_info_title">資本金</p>
      <p class="company_info_content">100万円</p>
    </li>
  </ul>
    </p>
</div> 

app/views/pages/contact.html.erb
<head>
	<% content_for :title do %>お問い合わせ -株式会社Easy- <% end %>
  <meta name="description" content="株式会社Easyのお問い合わせページ"/> 
</head>

<h1 class="page_title">お問い合わせ</h1>
	<div class="container contact">
		<div style="width:100%;height:600px;overflow:auto;-webkit-overflow-scrolling:touch;"><iframe src="https://tayori.com/form/76c986fb1e4f0f7c1b1d7c3527a3c57a20773b02" width="100%" height="100%"></iframe></div>
	</div>
  

app/views/pages/index.html.erb
  <div class="wrapper">

  <%= render :template => "pages/company" %>

  </div>

app/views/pages/service.html.erb
  <div class="wrapper">
    <main>
      <div class="container">
        <div class="service_all"><p>サービス一覧</p></div>
          <div class="service1">
            <div class="qotaelu_logo">
              <%= image_tag 'h_logo.jpg' , :size => '342x136' %>
            </div>
          </div>
          <div class="qotaelu_img">
          <%= image_tag 'qotaelu.png' , :size => '700x400' %>
          </div>
          <%# <p>報酬型qaサービスQotaelu</p> %>
          <div class="qotaelu_web">
          <a href="#" class="qotaelu_btn"><p>Webサービスへ</p></a>
          </div>
          <p class="line" id="company_form">
          </p>
        </div>
      </div>
    </main>
  </div>
  